apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
  - pipeline.yaml

commonLabels:
  pipeline: covid-detection
  version: v1.0.0
  model: monai-ensemble

commonAnnotations:
  git-sha: "TBD"
  build-date: "2025-12-28"
