apiVersion: v1
kind: PersistentVolume
metadata:
  name: covid-data-pv
  labels:
    type: local
    app: covid-pipeline
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: covid-data-pvc
  labels:
    app: covid-pipeline
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: local
      app: covid-pipeline