apiVersion: v1
kind: PersistentVolume
metadata:
  name: covid-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data
  storageClassName: standard
