apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubeflow

resources:
  - mysql-secret.yaml
  - mysql-pvc.yaml
  - mysql-statefulset.yaml

labels:
  - pairs:
      app: mysql
      component: infrastructure
      version: week6
