apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ml-pipelines
  namespace: argocd
spec:
  description: MONAI Kubeflow ML Pipelines
  sourceRepos:
    - 'https://github.com/NT114DevSecOpsProject/MONAI-Kubeflow-*'
    - '*'  # Allow all repos for easier testing
  destinations:
    - namespace: kubeflow
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Database and Scaling Infrastructure
  sourceRepos:
    - 'https://github.com/NT114DevSecOpsProject/MONAI-Kubeflow-*'
    - '*'  # Allow all repos for easier testing
  destinations:
    - namespace: kubeflow
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
